export const CREATE_LOOKOUT_RESULT_REQUEST = 'CREATE-LOOKOUT-RESULT-REQUEST';
export const CREATE_LOOKOUT_RESULT_SUCCESS = 'CREATE-LOOKOUT-RESULT-SUCCESS';
export const CREATE_LOOKOUT_RESULT_FAILURE = 'CREATE-LOOKOUT-RESULT-FAILURE';
export const GET_LOOKOUT_RESULT_REQUEST = 'GET-LOOKOUT-RESULT-REQUEST';
export const GET_LOOKOUT_RESULT_SUCCESS = 'GET-LOOKOUT-RESULT-SUCCESS';
export const GET_LOOKOUT_RESULT_FAILURE = 'GET-LOOKOUT-RESULT-FAILURE';
